### PR TITLE
Create newtest

### PR DESCRIPTION
**Pull request by nhaddadin**

### CODE REVIEW

**Comment by nhaddadin** [comment]
[run ci]

**Comment by esheikha** [comment]
Can one of the admins verify this patch?

**Comment by esheikha** [comment]
add to whitelist

**Comment by nhaddadin** [comment]
[run ci]

**Comment by nhaddadin** [comment]
[run ci ]

**Comment by nhaddadin** [comment]
[run ci]

**Comment by esheikha** [comment]
[run ci]

**Comment by esheikha** [comment]
[run ci]

**Pull request closed without merging**
